type Artist {
  artistId: ID!
  name: String
  imageUrl: String
  imageUrls: [String!]!
  artistBio: String
  artistMembers: String
  artistLocation: String
  artistLatitude: Float
  artistLongitude: Float
  artistActiveYearBegin: Int
  artistActiveYearEnd: Int
  artistFavorites: Float
  artistComments: Float
  tags: [String!]!
  albumCount: Int
  trackCount: Int
}

type ArtistSummary {
  artistId: ID!
  name: String
  imageUrl: String
}

type AlbumSummary {
  albumId: ID!
  title: String
  imageUrl: String
  type: String
}

type Album {
  albumId: ID!
  title: String
  imageUrl: String
  type: String
  dateReleased: String
  tracksCount: Int
  listens: Float
  favorites: Float
  comments: Float
  producer: String
  artists: [ArtistSummary!]!
}

type Track {
  trackId: ID!
  title: String
  imageUrl: String
  audioSrc: String
  durationSeconds: Int
  trackNumber: Int
  discNumber: Int
  isExplicit: Boolean!
  isInstrumental: Boolean!
  listens: Float
  favorites: Float
  comments: Float
  album: AlbumSummary
  mainArtists: [ArtistSummary!]!
  featArtists: [ArtistSummary!]!
  isLiked: Boolean!
}

type Playlist {
  playlistId: ID!
  name: String
  ownerDisplayName: String
  isEditable: Boolean!
  trackCount: Int!
  tracks: [Track!]!
}

type PlaylistSummary {
  playlistId: ID!
  name: String
  ownerDisplayName: String
  isEditable: Boolean!
  trackCount: Int!
}

enum PinnedItemType {
  TRACK
  ALBUM
  ARTIST
  PLAYLIST
}

type PinnedItem {
  slot: Int!
  itemType: PinnedItemType!
  pinnedAt: String!
  track: Track
  album: Album
  artist: ArtistSummary
  playlist: PlaylistSummary
}

type Account {
  accountId: ID!
  login: String
  email: String
  name: String
  isArtist: Boolean!
  artist: Artist
}

type AuthPayload {
  token: String!
  account: Account!
}

input CreateAccountInput {
  login: String!
  email: String!
  password: String!
  name: String!
  isArtist: Boolean
}

input UpdateArtistInput {
  artistBio: String
  artistLocation: String
  artistLatitude: Float
  artistLongitude: Float
  artistActiveYearBegin: Int
  artistActiveYearEnd: Int
  artistFavorites: Float
  artistComments: Float
}

input UpdateAccountInput {
  login: String
  email: String
  password: String
  name: String
  isArtist: Boolean
}

input CreatePlaylistInput {
  name: String!
}

input UpdatePlaylistInput {
  name: String
}

input LoginInput {
  email: String!
  password: String!
}

type Query {
  hello: String!
  account(accountId: String!): Account
  artist(artistId: String!): Artist
  artistAlbums(artistId: String!): [Album!]!
  track(trackId: String!): Track
  albumTracks(albumId: String!): [Track!]!
  artistTopTracks(artistId: String!, limit: Int): [Track!]!
  likedTracks: [Track!]!
  playlist(playlistId: String!): Playlist
  myPlaylists: [Playlist!]!
  myPinnedItems: [PinnedItem!]!
}

type Mutation {
  createAccount(input: CreateAccountInput!): Account!
  updateAccount(accountId: String!, input: UpdateAccountInput!): Account
  updateArtist(accountId: String!, input: UpdateArtistInput!): Artist
  deleteAccount(accountId: String!): Boolean!
  login(input: LoginInput!): AuthPayload
  logout: Boolean!
  likeTrack(trackId: String!): Track
  unlikeTrack(trackId: String!): Track
  pinTrack(slot: Int!, trackId: String!): PinnedItem
  pinAlbum(slot: Int!, albumId: String!): PinnedItem
  pinArtist(slot: Int!, artistId: String!): PinnedItem
  pinPlaylist(slot: Int!, playlistId: String!): PinnedItem
  unpinItem(slot: Int!): Boolean!
  createPlaylist(input: CreatePlaylistInput!): Playlist!
  updatePlaylist(playlistId: String!, input: UpdatePlaylistInput!): Playlist
  deletePlaylist(playlistId: String!): Boolean!
  addTrackToPlaylist(playlistId: String!, trackId: String!): Playlist
  removeTrackFromPlaylist(playlistId: String!, trackId: String!): Playlist
  recordTrackListen(trackId: String!): Boolean!
}
